# Netlify configuration for full-stack deployment
[build]
  # Build command for both frontend and functions
  command = "npm ci && cd frontend && npm ci && npm run build"
  
  # Directory to publish (frontend build output)
  publish = "frontend/dist"
  
  # Functions directory
  functions = "netlify/functions"
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "18"

# API routes to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA routing - must come after API redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set these in Netlify dashboard)
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"  
# JWT_SECRET = "your-jwt-secret"
# VITE_SUPABASE_URL = "your-supabase-url"
# VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"
# VITE_API_BASE_URL = "" (leave empty for same domain)

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Function-specific settings
[functions]
  # Increase timeout for video processing
  "*" = { timeout = 30 } 